name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: Bump Version on master
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}
          persist-credentials: false
          ref: ${{ github.ref }}
      - name: cat package.json
        run: cat ./package.json
      - name: Automated Version Bump
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: v
          patch-wording: 'fix, patch'
      - name: cat package.json
        run: cat ./package.json
      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
